---
resources:
  - name: cf
    type: cf
    source:
      api: ((cf-api))
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-space))
      skip_cert_check: true
  - name: scw-repo
    type: git
    source:
      uri: https://github.com/jacopen/springboot-concourse-workshop
      branch: user06

jobs:
  - name: unit-test
    plan:
      - get: scw-repo
        trigger: true
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: '8'
          inputs:
            - name: scw-repo
          run:
            path: bash
            args:
            - -c
            - |
              touch hoge.txt
  - name: build-artifact
    plan:
      - get: scw-repo
        trigger: true
        passed: [unit-test]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: '8'
          inputs:
            - name: scw-repo
          run:
            path: bash
            args:
            - -c
            - |
              touch hoga.txt
  